import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1761606223533 implements MigrationInterface {
    name = 'InitialSchema1761606223533'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE \`roles\` (\`id_rol\` int NOT NULL AUTO_INCREMENT, \`descripcion\` varchar(255) NOT NULL, \`activo\` bit NOT NULL, PRIMARY KEY (\`id_rol\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`roles_usuario\` (\`id_rol_usuario\` int NOT NULL AUTO_INCREMENT, \`id_usuario\` int NULL, \`id_rol\` int NULL, PRIMARY KEY (\`id_rol_usuario\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`sessions\` (\`id_session\` int NOT NULL AUTO_INCREMENT, \`token\` text NOT NULL, \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`update_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`id_usuario\` int NULL, UNIQUE INDEX \`REL_28c6203d0fc25270aee51ab355\` (\`id_usuario\`), PRIMARY KEY (\`id_session\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`usuarios\` (\`id_usuario\` int NOT NULL AUTO_INCREMENT, \`usuario\` varchar(255) NOT NULL, \`password\` varchar(255) NOT NULL, \`activo\` int NOT NULL DEFAULT '1', \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`update_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`id_empleado\` int NULL, UNIQUE INDEX \`REL_8469926fc9082fe7c3081e10cd\` (\`id_empleado\`), PRIMARY KEY (\`id_usuario\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`temperatura_casas\` (\`id_temperatura_casas\` int NOT NULL AUTO_INCREMENT, \`numero_casa\` int NOT NULL, \`temperatura\` double NOT NULL, \`caja\` int NOT NULL, \`id_ruta\` int NULL, PRIMARY KEY (\`id_temperatura_casas\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`leche_sala_extraccion_friam_016\` (\`id_leche_sala_extraccion\` int NOT NULL AUTO_INCREMENT, \`procedencia\` text NULL, \`consejeria\` int NULL, \`fecha_registro\` date NULL, \`id_madre_potencial\` int NULL, UNIQUE INDEX \`REL_d8efacad0437c9551da04da521\` (\`id_madre_potencial\`), PRIMARY KEY (\`id_leche_sala_extraccion\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`entradas_salidas_friam_012\` (\`id_entradas_salidas\` int NOT NULL AUTO_INCREMENT, \`fecha_vencimiento\` date NULL, \`procedencia\` text NULL, \`fecha_entrada\` date NULL, \`fecha_salida\` date NULL, \`id_madre_donante\` int NULL, \`responsable_entrada\` int NULL, \`responsable_salida\` int NULL, \`id_extraccion\` int NULL, \`id_frasco_recolectado\` int NULL, PRIMARY KEY (\`id_entradas_salidas\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`extraccion_friam_016\` (\`id_extraccion\` int NOT NULL AUTO_INCREMENT, \`cantidad\` float NULL, \`hora\` varchar(255) NULL, \`gaveta\` int NULL, \`fecha_extraccion\` date NULL, \`motivo_consulta\` text NULL, \`observaciones\` text NULL, \`id_congelador\` int NULL, \`id_leche_sala_extraccion\` int NULL, PRIMARY KEY (\`id_extraccion\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`congelador\` (\`id_congelador\` int NOT NULL AUTO_INCREMENT, \`descripcion\` varchar(255) NOT NULL, PRIMARY KEY (\`id_congelador\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`frascos_recolectados\` (\`id_frascos_recolectados\` int NOT NULL AUTO_INCREMENT, \`volumen\` double NOT NULL, \`fecha_de_extraccion\` date NOT NULL, \`termo\` int NOT NULL, \`gaveta\` int NOT NULL, \`id_congelador\` int NULL, \`id_casa_visita\` int NULL, PRIMARY KEY (\`id_frascos_recolectados\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`casas_visitas\` (\`id_casa_visita\` int NOT NULL AUTO_INCREMENT, \`observacion\` text NULL, \`numero_casa\` int NOT NULL, \`id_ruta\` int NULL, \`id_madre_donante\` int NULL, PRIMARY KEY (\`id_casa_visita\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`temperaturas_rutas\` (\`id_temperatura_ruta\` int NOT NULL AUTO_INCREMENT, \`numero_caja\` int NOT NULL, \`temperatura_salida\` double NOT NULL, \`temperatura_llegada\` double NULL, \`id_ruta\` int NULL, PRIMARY KEY (\`id_temperatura_ruta\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`rutas_recoleccion_friam_011\` (\`id_ruta\` int NOT NULL AUTO_INCREMENT, \`fecha_registro\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`jornada\` text NOT NULL, \`nombre_conductor\` text NOT NULL, \`placa_vehiculo\` varchar(255) NOT NULL, \`kilometraje_inicial\` double NOT NULL, \`kilometraje_final\` double NULL, \`hora_salida\` varchar(255) NULL, \`hora_llegada\` varchar(255) NULL, \`total_visitas\` int NULL, \`volumen_total\` double NULL, \`id_empleado\` int NULL, PRIMARY KEY (\`id_ruta\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`leche_distribucion_frhos_063\` (\`id_leche_distribucion\` int NOT NULL AUTO_INCREMENT, \`fecha\` date NOT NULL, \`volumen_manana\` float NULL, \`volumen_tarde\` float NULL, \`perdidas\` float NULL, \`id_madre_potencial\` int NULL, \`id_empleado\` int NULL, PRIMARY KEY (\`id_leche_distribucion\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`empleados\` (\`id_empleado\` int NOT NULL AUTO_INCREMENT, \`nombre\` varchar(255) NOT NULL, \`cargo\` varchar(255) NOT NULL, \`telefono\` int NOT NULL, \`correo\` varchar(255) NULL, \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`update_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id_empleado\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`entidades\` (\`id_entidad\` int NOT NULL AUTO_INCREMENT, \`nombre\` varchar(255) NOT NULL, \`activo\` int NOT NULL, PRIMARY KEY (\`id_entidad\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`info_madres\` (\`id_info_madre\` int NOT NULL AUTO_INCREMENT, \`nombre\` varchar(255) NOT NULL, \`apellido\` varchar(255) NOT NULL, \`documento\` varchar(255) NOT NULL, \`fecha_nacimiento\` date NOT NULL, \`fecha_parto\` date NULL, \`telefono\` varchar(255) NULL, \`celular\` varchar(255) NULL, \`departamento\` varchar(255) NULL, \`ciudad\` varchar(255) NULL, \`barrio\` varchar(255) NULL, \`direccion\` varchar(255) NULL, \`profesion\` varchar(255) NULL, \`eps\` varchar(255) NULL, PRIMARY KEY (\`id_info_madre\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`tipo_laboratorio\` (\`id_tipo_laboratorio\` int NOT NULL AUTO_INCREMENT, \`nombre\` varchar(255) NOT NULL, PRIMARY KEY (\`id_tipo_laboratorio\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`laboratorios\` (\`id_laboratorios\` int NOT NULL AUTO_INCREMENT, \`resultado\` int NOT NULL, \`fecha_vencimiento\` date NOT NULL, \`documento\` text NOT NULL, \`fecha_registro\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`id_tipo_laboratorio\` int NULL, \`id_madre_potencial\` int NULL, PRIMARY KEY (\`id_laboratorios\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`evaluacion_lactancia\` (\`id_evaluacion_lactancia\` int NOT NULL AUTO_INCREMENT, \`madre\` text NOT NULL, \`bebe\` text NOT NULL, \`pechos\` text NOT NULL, \`posicion_bebe\` text NOT NULL, \`agarre_pecho\` text NOT NULL, \`succion\` text NOT NULL, \`deglucion\` text NOT NULL, PRIMARY KEY (\`id_evaluacion_lactancia\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`clasificacion_preguntas\` (\`id_clasificacion_preguntas\` int NOT NULL AUTO_INCREMENT, \`descripcion\` text NOT NULL, PRIMARY KEY (\`id_clasificacion_preguntas\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`preguntas_friam_037\` (\`id_pregunta_friam037\` int NOT NULL AUTO_INCREMENT, \`descripcion\` text NOT NULL, \`id_clasificacion_pregunta\` int NULL, PRIMARY KEY (\`id_pregunta_friam037\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`respuestas_friam_037\` (\`id_respuesta\` int NOT NULL AUTO_INCREMENT, \`respuesta\` int NULL, \`id_pregunta\` int NULL, \`id_visita_domiciliario\` int NULL, PRIMARY KEY (\`id_respuesta\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`visita_domiciliaria_friam_037\` (\`id_visita\` int NOT NULL AUTO_INCREMENT, \`observaciones\` text NULL, \`recomendaciones\` text NULL, \`donante_efectiva\` int NULL, \`firma_usuario\` text NULL, \`firma_evaluador\` text NULL, \`id_madre_potencial\` int NULL, \`id_evaluacion_lactancia\` int NULL, UNIQUE INDEX \`REL_fbf6224f2c6f33457dbc4d0be7\` (\`id_madre_potencial\`), UNIQUE INDEX \`REL_1633ea2dc37714bd763acbcc3a\` (\`id_evaluacion_lactancia\`), PRIMARY KEY (\`id_visita\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`madres_potenciales\` (\`id_madre_potencial\` int NOT NULL AUTO_INCREMENT, \`educacion_presencial\` int NULL, \`fecha_llamada\` date NULL, \`llamada\` enum ('saliente', 'entrante') NULL, \`asesoria\` int NULL, \`donante_efectiva\` int NULL, \`fecha_visita\` date NULL, \`observacion\` text NULL, \`fecha_registro\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`id_entidad\` int NULL, \`id_empleado\` int NULL, \`id_info_madre\` int NULL, UNIQUE INDEX \`REL_2d4cf3dcde30c89e0a109f2963\` (\`id_info_madre\`), PRIMARY KEY (\`id_madre_potencial\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`hijos_madres\` (\`id_hijos_madres\` int NOT NULL AUTO_INCREMENT, \`nombre\` varchar(255) NOT NULL, \`peso\` double NOT NULL, \`id_madres_donantes\` int NULL, PRIMARY KEY (\`id_hijos_madres\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`gestacion\` (\`id_gestacion\` int NOT NULL AUTO_INCREMENT, \`lugar_control_prenatal\` text NOT NULL, \`asistio_control_prenatal\` int NOT NULL, \`tipo_ips\` int NOT NULL, \`peso_gestacion_inicial\` double NOT NULL, \`peso_gestacion_final\` double NOT NULL, \`talla\` float NOT NULL, \`parto_a_termino\` int NOT NULL, \`pre_termino\` int NOT NULL, \`semanas\` int NOT NULL, \`fecha_parto\` date NOT NULL, \`id_madre_donante\` int NULL, UNIQUE INDEX \`REL_d4e4c2827125c46c9804270645\` (\`id_madre_donante\`), PRIMARY KEY (\`id_gestacion\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`examenes_prenatal\` (\`id_examenes_prenatal\` int NOT NULL AUTO_INCREMENT, \`hemoglobina\` int NOT NULL, \`hematocrito\` int NOT NULL, \`transfuciones\` int NOT NULL, \`enfermedades_gestacion\` text NOT NULL, \`fuma\` int NOT NULL, \`alcohol\` int NOT NULL, \`id_madre_donante\` int NULL, UNIQUE INDEX \`REL_ead7a9dd59defcdf661bc2162e\` (\`id_madre_donante\`), PRIMARY KEY (\`id_examenes_prenatal\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`medicamentos\` (\`id_medicamentos\` int NOT NULL AUTO_INCREMENT, \`medicamento\` text NOT NULL, \`psicoactivos\` text NOT NULL, \`id_madre_donante\` int NULL, UNIQUE INDEX \`REL_a3cab5c8691832df9c446fac3d\` (\`id_madre_donante\`), PRIMARY KEY (\`id_medicamentos\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`madres_donantes_friam_018\` (\`id_madre_donante\` int NOT NULL AUTO_INCREMENT, \`donante_exclusivo\` int NOT NULL, \`tipo_donante\` enum ('interna', 'externa') NOT NULL, \`recoleccion_domicilio\` int NOT NULL, \`capacitado\` varchar(255) NOT NULL, \`recibio_educacion\` text NOT NULL, \`donante_apta\` int NULL, \`firma_donante\` text NULL, \`firma_profesional\` text NULL, \`firma_acompañante\` text NULL, \`activo\` int NOT NULL DEFAULT '1', \`fecha_diligenciamiento\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`id_madre_potencial\` int NULL, \`id_empleado\` int NULL, UNIQUE INDEX \`REL_41da793ff71343562989199d51\` (\`id_madre_potencial\`), PRIMARY KEY (\`id_madre_donante\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`datos_visita_seguimiento\` (\`id_datos_visita\` int NOT NULL AUTO_INCREMENT, \`observaciones\` text NULL, \`recomendaciones\` text NULL, \`firma_usuario\` text NULL, \`firma_evaluador\` text NULL, \`id_visita_seguimiento\` int NULL, UNIQUE INDEX \`REL_78ba710db8b09bd0447a88d12c\` (\`id_visita_seguimiento\`), PRIMARY KEY (\`id_datos_visita\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`preguntas_friam_038\` (\`id_pregunta\` int NOT NULL AUTO_INCREMENT, \`pregunta\` text NOT NULL, PRIMARY KEY (\`id_pregunta\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`respuestas_friam_038\` (\`id_respuesta\` int NOT NULL AUTO_INCREMENT, \`respuesta\` int NOT NULL, \`id_pregunta\` int NULL, \`id_visita_domiciliario\` int NULL, PRIMARY KEY (\`id_respuesta\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`visita_seguimiento_friam_038\` (\`id_visita_seguimiento\` int NOT NULL AUTO_INCREMENT, \`fecha\` date NOT NULL, PRIMARY KEY (\`id_visita_seguimiento\`)) ENGINE=InnoDB`);
        await queryRunner.query(`ALTER TABLE \`roles_usuario\` ADD CONSTRAINT \`FK_8bae8214f9f2b55f39d9346b0df\` FOREIGN KEY (\`id_usuario\`) REFERENCES \`usuarios\`(\`id_usuario\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`roles_usuario\` ADD CONSTRAINT \`FK_64aa663ece24eab4d3b661b8318\` FOREIGN KEY (\`id_rol\`) REFERENCES \`roles\`(\`id_rol\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`sessions\` ADD CONSTRAINT \`FK_28c6203d0fc25270aee51ab3550\` FOREIGN KEY (\`id_usuario\`) REFERENCES \`usuarios\`(\`id_usuario\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`usuarios\` ADD CONSTRAINT \`FK_8469926fc9082fe7c3081e10cd3\` FOREIGN KEY (\`id_empleado\`) REFERENCES \`empleados\`(\`id_empleado\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`temperatura_casas\` ADD CONSTRAINT \`FK_bd7e5d898eb8c29998b1ff435ba\` FOREIGN KEY (\`id_ruta\`) REFERENCES \`rutas_recoleccion_friam_011\`(\`id_ruta\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`leche_sala_extraccion_friam_016\` ADD CONSTRAINT \`FK_d8efacad0437c9551da04da521e\` FOREIGN KEY (\`id_madre_potencial\`) REFERENCES \`madres_potenciales\`(\`id_madre_potencial\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`entradas_salidas_friam_012\` ADD CONSTRAINT \`FK_ed01470b6a004857c2277c9a5e7\` FOREIGN KEY (\`id_madre_donante\`) REFERENCES \`madres_donantes_friam_018\`(\`id_madre_donante\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`entradas_salidas_friam_012\` ADD CONSTRAINT \`FK_66f4a237a72e3732b40cc842124\` FOREIGN KEY (\`responsable_entrada\`) REFERENCES \`empleados\`(\`id_empleado\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`entradas_salidas_friam_012\` ADD CONSTRAINT \`FK_82c5a5aae0be2e0f0c3ca7bee55\` FOREIGN KEY (\`responsable_salida\`) REFERENCES \`empleados\`(\`id_empleado\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`entradas_salidas_friam_012\` ADD CONSTRAINT \`FK_bdb83d381cf5c143c422380753a\` FOREIGN KEY (\`id_extraccion\`) REFERENCES \`extraccion_friam_016\`(\`id_extraccion\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`entradas_salidas_friam_012\` ADD CONSTRAINT \`FK_751fa147d0efdb6d2179c4f202b\` FOREIGN KEY (\`id_frasco_recolectado\`) REFERENCES \`frascos_recolectados\`(\`id_frascos_recolectados\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`extraccion_friam_016\` ADD CONSTRAINT \`FK_5c2853fdaff133d0ac8cca6e630\` FOREIGN KEY (\`id_congelador\`) REFERENCES \`congelador\`(\`id_congelador\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`extraccion_friam_016\` ADD CONSTRAINT \`FK_58236e9d09fcf271242c563f627\` FOREIGN KEY (\`id_leche_sala_extraccion\`) REFERENCES \`leche_sala_extraccion_friam_016\`(\`id_leche_sala_extraccion\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`frascos_recolectados\` ADD CONSTRAINT \`FK_bc68b3c8350abd5849248455531\` FOREIGN KEY (\`id_congelador\`) REFERENCES \`congelador\`(\`id_congelador\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`frascos_recolectados\` ADD CONSTRAINT \`FK_27fb5a6e6c788fed1d042795569\` FOREIGN KEY (\`id_casa_visita\`) REFERENCES \`casas_visitas\`(\`id_casa_visita\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`casas_visitas\` ADD CONSTRAINT \`FK_e92ed61c8c8926fdd81cc9cc638\` FOREIGN KEY (\`id_ruta\`) REFERENCES \`rutas_recoleccion_friam_011\`(\`id_ruta\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`casas_visitas\` ADD CONSTRAINT \`FK_7a6a320f8d34398bd7ea1a50089\` FOREIGN KEY (\`id_madre_donante\`) REFERENCES \`madres_donantes_friam_018\`(\`id_madre_donante\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`temperaturas_rutas\` ADD CONSTRAINT \`FK_d7ba444faf1a9246331b6905056\` FOREIGN KEY (\`id_ruta\`) REFERENCES \`rutas_recoleccion_friam_011\`(\`id_ruta\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`rutas_recoleccion_friam_011\` ADD CONSTRAINT \`FK_e39f27423ee27ed8f65017fadcb\` FOREIGN KEY (\`id_empleado\`) REFERENCES \`empleados\`(\`id_empleado\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`leche_distribucion_frhos_063\` ADD CONSTRAINT \`FK_6ec51aaf89275128b9cba81e72b\` FOREIGN KEY (\`id_madre_potencial\`) REFERENCES \`madres_potenciales\`(\`id_madre_potencial\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`leche_distribucion_frhos_063\` ADD CONSTRAINT \`FK_0ff8ab69b560eb2b3bc1c02b367\` FOREIGN KEY (\`id_empleado\`) REFERENCES \`empleados\`(\`id_empleado\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`laboratorios\` ADD CONSTRAINT \`FK_2795cd1d07b36cdaf4e5eebc782\` FOREIGN KEY (\`id_tipo_laboratorio\`) REFERENCES \`tipo_laboratorio\`(\`id_tipo_laboratorio\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`laboratorios\` ADD CONSTRAINT \`FK_d2ae7a47a59503250cf66977b64\` FOREIGN KEY (\`id_madre_potencial\`) REFERENCES \`madres_potenciales\`(\`id_madre_potencial\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`preguntas_friam_037\` ADD CONSTRAINT \`FK_29e9c97493b01c6324979cced73\` FOREIGN KEY (\`id_clasificacion_pregunta\`) REFERENCES \`clasificacion_preguntas\`(\`id_clasificacion_preguntas\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`respuestas_friam_037\` ADD CONSTRAINT \`FK_280c3cec338ab214221b0a9572b\` FOREIGN KEY (\`id_pregunta\`) REFERENCES \`preguntas_friam_037\`(\`id_pregunta_friam037\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`respuestas_friam_037\` ADD CONSTRAINT \`FK_efb842cdafd5b7170422192a921\` FOREIGN KEY (\`id_visita_domiciliario\`) REFERENCES \`visita_domiciliaria_friam_037\`(\`id_visita\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`visita_domiciliaria_friam_037\` ADD CONSTRAINT \`FK_fbf6224f2c6f33457dbc4d0be7c\` FOREIGN KEY (\`id_madre_potencial\`) REFERENCES \`madres_potenciales\`(\`id_madre_potencial\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`visita_domiciliaria_friam_037\` ADD CONSTRAINT \`FK_1633ea2dc37714bd763acbcc3ad\` FOREIGN KEY (\`id_evaluacion_lactancia\`) REFERENCES \`evaluacion_lactancia\`(\`id_evaluacion_lactancia\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`madres_potenciales\` ADD CONSTRAINT \`FK_db2e2e0169a763b580bd1d358e9\` FOREIGN KEY (\`id_entidad\`) REFERENCES \`entidades\`(\`id_entidad\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`madres_potenciales\` ADD CONSTRAINT \`FK_1e31c4ec2202b8b1b385f472805\` FOREIGN KEY (\`id_empleado\`) REFERENCES \`empleados\`(\`id_empleado\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`madres_potenciales\` ADD CONSTRAINT \`FK_2d4cf3dcde30c89e0a109f29633\` FOREIGN KEY (\`id_info_madre\`) REFERENCES \`info_madres\`(\`id_info_madre\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`hijos_madres\` ADD CONSTRAINT \`FK_721b3389814aa7ac3f91d6e65be\` FOREIGN KEY (\`id_madres_donantes\`) REFERENCES \`madres_donantes_friam_018\`(\`id_madre_donante\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`gestacion\` ADD CONSTRAINT \`FK_d4e4c2827125c46c98042706457\` FOREIGN KEY (\`id_madre_donante\`) REFERENCES \`madres_donantes_friam_018\`(\`id_madre_donante\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`examenes_prenatal\` ADD CONSTRAINT \`FK_ead7a9dd59defcdf661bc2162e6\` FOREIGN KEY (\`id_madre_donante\`) REFERENCES \`madres_donantes_friam_018\`(\`id_madre_donante\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`medicamentos\` ADD CONSTRAINT \`FK_a3cab5c8691832df9c446fac3da\` FOREIGN KEY (\`id_madre_donante\`) REFERENCES \`madres_donantes_friam_018\`(\`id_madre_donante\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`madres_donantes_friam_018\` ADD CONSTRAINT \`FK_41da793ff71343562989199d51d\` FOREIGN KEY (\`id_madre_potencial\`) REFERENCES \`madres_potenciales\`(\`id_madre_potencial\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`madres_donantes_friam_018\` ADD CONSTRAINT \`FK_015de2b97ae506d5c510759f103\` FOREIGN KEY (\`id_empleado\`) REFERENCES \`empleados\`(\`id_empleado\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`datos_visita_seguimiento\` ADD CONSTRAINT \`FK_78ba710db8b09bd0447a88d12cc\` FOREIGN KEY (\`id_visita_seguimiento\`) REFERENCES \`visita_seguimiento_friam_038\`(\`id_visita_seguimiento\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`respuestas_friam_038\` ADD CONSTRAINT \`FK_df92ff2e4cd72657372adb268df\` FOREIGN KEY (\`id_pregunta\`) REFERENCES \`preguntas_friam_038\`(\`id_pregunta\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`respuestas_friam_038\` ADD CONSTRAINT \`FK_c6ee9e4b6a9e02cbc65a5a5fe72\` FOREIGN KEY (\`id_visita_domiciliario\`) REFERENCES \`visita_seguimiento_friam_038\`(\`id_visita_seguimiento\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`visita_seguimiento_friam_038\` ADD CONSTRAINT \`FK_ce0da0b464f634343ce70db1991\` FOREIGN KEY (\`id_visita_seguimiento\`) REFERENCES \`madres_donantes_friam_018\`(\`id_madre_donante\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`visita_seguimiento_friam_038\` DROP FOREIGN KEY \`FK_ce0da0b464f634343ce70db1991\``);
        await queryRunner.query(`ALTER TABLE \`respuestas_friam_038\` DROP FOREIGN KEY \`FK_c6ee9e4b6a9e02cbc65a5a5fe72\``);
        await queryRunner.query(`ALTER TABLE \`respuestas_friam_038\` DROP FOREIGN KEY \`FK_df92ff2e4cd72657372adb268df\``);
        await queryRunner.query(`ALTER TABLE \`datos_visita_seguimiento\` DROP FOREIGN KEY \`FK_78ba710db8b09bd0447a88d12cc\``);
        await queryRunner.query(`ALTER TABLE \`madres_donantes_friam_018\` DROP FOREIGN KEY \`FK_015de2b97ae506d5c510759f103\``);
        await queryRunner.query(`ALTER TABLE \`madres_donantes_friam_018\` DROP FOREIGN KEY \`FK_41da793ff71343562989199d51d\``);
        await queryRunner.query(`ALTER TABLE \`medicamentos\` DROP FOREIGN KEY \`FK_a3cab5c8691832df9c446fac3da\``);
        await queryRunner.query(`ALTER TABLE \`examenes_prenatal\` DROP FOREIGN KEY \`FK_ead7a9dd59defcdf661bc2162e6\``);
        await queryRunner.query(`ALTER TABLE \`gestacion\` DROP FOREIGN KEY \`FK_d4e4c2827125c46c98042706457\``);
        await queryRunner.query(`ALTER TABLE \`hijos_madres\` DROP FOREIGN KEY \`FK_721b3389814aa7ac3f91d6e65be\``);
        await queryRunner.query(`ALTER TABLE \`madres_potenciales\` DROP FOREIGN KEY \`FK_2d4cf3dcde30c89e0a109f29633\``);
        await queryRunner.query(`ALTER TABLE \`madres_potenciales\` DROP FOREIGN KEY \`FK_1e31c4ec2202b8b1b385f472805\``);
        await queryRunner.query(`ALTER TABLE \`madres_potenciales\` DROP FOREIGN KEY \`FK_db2e2e0169a763b580bd1d358e9\``);
        await queryRunner.query(`ALTER TABLE \`visita_domiciliaria_friam_037\` DROP FOREIGN KEY \`FK_1633ea2dc37714bd763acbcc3ad\``);
        await queryRunner.query(`ALTER TABLE \`visita_domiciliaria_friam_037\` DROP FOREIGN KEY \`FK_fbf6224f2c6f33457dbc4d0be7c\``);
        await queryRunner.query(`ALTER TABLE \`respuestas_friam_037\` DROP FOREIGN KEY \`FK_efb842cdafd5b7170422192a921\``);
        await queryRunner.query(`ALTER TABLE \`respuestas_friam_037\` DROP FOREIGN KEY \`FK_280c3cec338ab214221b0a9572b\``);
        await queryRunner.query(`ALTER TABLE \`preguntas_friam_037\` DROP FOREIGN KEY \`FK_29e9c97493b01c6324979cced73\``);
        await queryRunner.query(`ALTER TABLE \`laboratorios\` DROP FOREIGN KEY \`FK_d2ae7a47a59503250cf66977b64\``);
        await queryRunner.query(`ALTER TABLE \`laboratorios\` DROP FOREIGN KEY \`FK_2795cd1d07b36cdaf4e5eebc782\``);
        await queryRunner.query(`ALTER TABLE \`leche_distribucion_frhos_063\` DROP FOREIGN KEY \`FK_0ff8ab69b560eb2b3bc1c02b367\``);
        await queryRunner.query(`ALTER TABLE \`leche_distribucion_frhos_063\` DROP FOREIGN KEY \`FK_6ec51aaf89275128b9cba81e72b\``);
        await queryRunner.query(`ALTER TABLE \`rutas_recoleccion_friam_011\` DROP FOREIGN KEY \`FK_e39f27423ee27ed8f65017fadcb\``);
        await queryRunner.query(`ALTER TABLE \`temperaturas_rutas\` DROP FOREIGN KEY \`FK_d7ba444faf1a9246331b6905056\``);
        await queryRunner.query(`ALTER TABLE \`casas_visitas\` DROP FOREIGN KEY \`FK_7a6a320f8d34398bd7ea1a50089\``);
        await queryRunner.query(`ALTER TABLE \`casas_visitas\` DROP FOREIGN KEY \`FK_e92ed61c8c8926fdd81cc9cc638\``);
        await queryRunner.query(`ALTER TABLE \`frascos_recolectados\` DROP FOREIGN KEY \`FK_27fb5a6e6c788fed1d042795569\``);
        await queryRunner.query(`ALTER TABLE \`frascos_recolectados\` DROP FOREIGN KEY \`FK_bc68b3c8350abd5849248455531\``);
        await queryRunner.query(`ALTER TABLE \`extraccion_friam_016\` DROP FOREIGN KEY \`FK_58236e9d09fcf271242c563f627\``);
        await queryRunner.query(`ALTER TABLE \`extraccion_friam_016\` DROP FOREIGN KEY \`FK_5c2853fdaff133d0ac8cca6e630\``);
        await queryRunner.query(`ALTER TABLE \`entradas_salidas_friam_012\` DROP FOREIGN KEY \`FK_751fa147d0efdb6d2179c4f202b\``);
        await queryRunner.query(`ALTER TABLE \`entradas_salidas_friam_012\` DROP FOREIGN KEY \`FK_bdb83d381cf5c143c422380753a\``);
        await queryRunner.query(`ALTER TABLE \`entradas_salidas_friam_012\` DROP FOREIGN KEY \`FK_82c5a5aae0be2e0f0c3ca7bee55\``);
        await queryRunner.query(`ALTER TABLE \`entradas_salidas_friam_012\` DROP FOREIGN KEY \`FK_66f4a237a72e3732b40cc842124\``);
        await queryRunner.query(`ALTER TABLE \`entradas_salidas_friam_012\` DROP FOREIGN KEY \`FK_ed01470b6a004857c2277c9a5e7\``);
        await queryRunner.query(`ALTER TABLE \`leche_sala_extraccion_friam_016\` DROP FOREIGN KEY \`FK_d8efacad0437c9551da04da521e\``);
        await queryRunner.query(`ALTER TABLE \`temperatura_casas\` DROP FOREIGN KEY \`FK_bd7e5d898eb8c29998b1ff435ba\``);
        await queryRunner.query(`ALTER TABLE \`usuarios\` DROP FOREIGN KEY \`FK_8469926fc9082fe7c3081e10cd3\``);
        await queryRunner.query(`ALTER TABLE \`sessions\` DROP FOREIGN KEY \`FK_28c6203d0fc25270aee51ab3550\``);
        await queryRunner.query(`ALTER TABLE \`roles_usuario\` DROP FOREIGN KEY \`FK_64aa663ece24eab4d3b661b8318\``);
        await queryRunner.query(`ALTER TABLE \`roles_usuario\` DROP FOREIGN KEY \`FK_8bae8214f9f2b55f39d9346b0df\``);
        await queryRunner.query(`DROP TABLE \`visita_seguimiento_friam_038\``);
        await queryRunner.query(`DROP TABLE \`respuestas_friam_038\``);
        await queryRunner.query(`DROP TABLE \`preguntas_friam_038\``);
        await queryRunner.query(`DROP INDEX \`REL_78ba710db8b09bd0447a88d12c\` ON \`datos_visita_seguimiento\``);
        await queryRunner.query(`DROP TABLE \`datos_visita_seguimiento\``);
        await queryRunner.query(`DROP INDEX \`REL_41da793ff71343562989199d51\` ON \`madres_donantes_friam_018\``);
        await queryRunner.query(`DROP TABLE \`madres_donantes_friam_018\``);
        await queryRunner.query(`DROP INDEX \`REL_a3cab5c8691832df9c446fac3d\` ON \`medicamentos\``);
        await queryRunner.query(`DROP TABLE \`medicamentos\``);
        await queryRunner.query(`DROP INDEX \`REL_ead7a9dd59defcdf661bc2162e\` ON \`examenes_prenatal\``);
        await queryRunner.query(`DROP TABLE \`examenes_prenatal\``);
        await queryRunner.query(`DROP INDEX \`REL_d4e4c2827125c46c9804270645\` ON \`gestacion\``);
        await queryRunner.query(`DROP TABLE \`gestacion\``);
        await queryRunner.query(`DROP TABLE \`hijos_madres\``);
        await queryRunner.query(`DROP INDEX \`REL_2d4cf3dcde30c89e0a109f2963\` ON \`madres_potenciales\``);
        await queryRunner.query(`DROP TABLE \`madres_potenciales\``);
        await queryRunner.query(`DROP INDEX \`REL_1633ea2dc37714bd763acbcc3a\` ON \`visita_domiciliaria_friam_037\``);
        await queryRunner.query(`DROP INDEX \`REL_fbf6224f2c6f33457dbc4d0be7\` ON \`visita_domiciliaria_friam_037\``);
        await queryRunner.query(`DROP TABLE \`visita_domiciliaria_friam_037\``);
        await queryRunner.query(`DROP TABLE \`respuestas_friam_037\``);
        await queryRunner.query(`DROP TABLE \`preguntas_friam_037\``);
        await queryRunner.query(`DROP TABLE \`clasificacion_preguntas\``);
        await queryRunner.query(`DROP TABLE \`evaluacion_lactancia\``);
        await queryRunner.query(`DROP TABLE \`laboratorios\``);
        await queryRunner.query(`DROP TABLE \`tipo_laboratorio\``);
        await queryRunner.query(`DROP TABLE \`info_madres\``);
        await queryRunner.query(`DROP TABLE \`entidades\``);
        await queryRunner.query(`DROP TABLE \`empleados\``);
        await queryRunner.query(`DROP TABLE \`leche_distribucion_frhos_063\``);
        await queryRunner.query(`DROP TABLE \`rutas_recoleccion_friam_011\``);
        await queryRunner.query(`DROP TABLE \`temperaturas_rutas\``);
        await queryRunner.query(`DROP TABLE \`casas_visitas\``);
        await queryRunner.query(`DROP TABLE \`frascos_recolectados\``);
        await queryRunner.query(`DROP TABLE \`congelador\``);
        await queryRunner.query(`DROP TABLE \`extraccion_friam_016\``);
        await queryRunner.query(`DROP TABLE \`entradas_salidas_friam_012\``);
        await queryRunner.query(`DROP INDEX \`REL_d8efacad0437c9551da04da521\` ON \`leche_sala_extraccion_friam_016\``);
        await queryRunner.query(`DROP TABLE \`leche_sala_extraccion_friam_016\``);
        await queryRunner.query(`DROP TABLE \`temperatura_casas\``);
        await queryRunner.query(`DROP INDEX \`REL_8469926fc9082fe7c3081e10cd\` ON \`usuarios\``);
        await queryRunner.query(`DROP TABLE \`usuarios\``);
        await queryRunner.query(`DROP INDEX \`REL_28c6203d0fc25270aee51ab355\` ON \`sessions\``);
        await queryRunner.query(`DROP TABLE \`sessions\``);
        await queryRunner.query(`DROP TABLE \`roles_usuario\``);
        await queryRunner.query(`DROP TABLE \`roles\``);
    }

}
